### ISSUE TITLE
Error after entering phone, email, adress, country etc.

### ISSUE THREAD

**Issue by mathwhiz1212** [Daplie/daplie-tools#15]
Installed using npm earlier today. Seems similiar to https://github.com/Daplie/daplie-tools/issues/12.

Possibly Unhandled Rejection at:
[TypeError: Cannot read property '0' of undefined]

**Comment by coolaj86** [comment]
I fixed #12, it was different than this.

Unfortunately that's about the least helpful error message in the history of error messages. Admittedly it's better than `undefined` and certainly better than feigned `success`...


Try changing https://github.com/Daplie/daplie-tools/blob/master/bin/daplie.js#L1032 to this and let me know if you can get the error again.

```js
console.error(reason.stack || reason);
```

**Comment by coolaj86** [comment]
Meanwhile I'll try to get it myself by creating a new account.

**Comment by coolaj86** [comment]
Or I'll just look at the code and find it on the first try:
https://github.com/OAuth3/oauth3-cli/blob/master/lib/index.js#L1594

This is what happens when we run custom builds...
