### ISSUE TITLE
Weird devices:list bug

### ISSUE THREAD

**Issue by mathwhiz1212** [Daplie/daplie-tools#19]
Look at the date on the middle one. I can just remove it if no one else is having this issue.

```daplie devices:list```

Result:

```COMMITTED AT		DEVICE NAME 	ADDRESSES```

```Wed Apr 20 2016 21:56:28 GMT+0000 (UTC)	name	IP```

```Thu Jan 01 1970 00:00:00 GMT+0000 (UTC)	        localhost		127.0.0.1,::1```

```Wed Apr 20 2016 22:09:15 GMT+0000 (UTC)	name	IP```

**Comment by coolaj86** [comment]
Can you find where to console.log the raw json and post that?

**Comment by mathwhiz1212** [comment]
I registered some new domains and this problem has diappeared.
