### ISSUE TITLE
Error when searching for domains.

### ISSUE THREAD

**Issue by mathwhiz1212** [Daplie/daplie-tools#2]
When trying to search domains I get this error: (running as root works fine for searching.)

Search Domains: { [Error: EACCES: permission denied, open '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.tmp1.json']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.tmp1.json' }
{ [Error: EACCES: permission denied, open '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.tmp2.json']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.tmp2.json' }
{ [Error: ENOENT: no such file or directory, unlink '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.bak.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.bak.json' }
{ [Error: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.tmp2.json' -> '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.bak.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.tmp2.json',
  dest: '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.bak.json' }
{ [Error: ENOENT: no such file or directory, unlink '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.json' }
{ [Error: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.tmp1.json' -> '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.tmp1.json',
  dest: '/usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.json' }

**Comment by mathwhiz1212** [comment]
Error is gone and I am unable to replicate. (Not running as root.)

**Comment by mathwhiz1212** [comment]
I tried this on another machine and it gives the same error until your run it once as root then it is fine.

**Comment by coolaj86** [comment]
That's a problem with your node installation, not this program.

Try this:

```bash
sudo chown -R "$(whoami)" /usr/local/
```
