### ISSUE TITLE
Will not advance beyond the tips page.

### ISSUE THREAD

**Issue by mathwhiz1212** [Daplie/daplie-tools#3]
It won't go beyond the tips page if you don't tip anything.

We appreciate tips!                                                                                                       
Give an extra buck for R&D of Awesomeness?

Tip Amount (i.e. 0, 1, 5, 10): $

**Comment by coolaj86** [comment]
You can put 0.

**Comment by mathwhiz1212** [comment]
Sorry I wasn't clear. That was what I was referring to. If I enter 0 and hit enter it will go right back to the tips page. Re-installed and tested today with same problem on both my server and my desktop.

**Comment by coolaj86** [comment]
Confirmed. Looking into it further.

**Comment by coolaj86** [comment]
should be fixed now

**Comment by mathwhiz1212** [comment]
It is fixed now.
